export const attendanceConstants = {
  SET_ATTENDANCES: 'SET_ATTENDANCES',
  ATTENDANCE_REQUEST: 'ATTENDANCE_REQUEST',
  ATTENDANCE_FAILURE: 'ATTENDANCE_FAILURE',
  ATTENDANCE_SUCCESS: 'ATTENDANCE_SUCCESS',
  CREATE_ATTENDANCE_REQUEST: 'CREATE_ATTENDANCE_REQUEST',
  CREATE_ATTENDANCE_SUCCESS: 'CREATE_ATTENDANCE_SUCCESS',
  CREATE_ATTENDANCE_FAILED: 'CREATE_ATTENDANCE_FAILED'
};
